name: Generate Thumbnails for FreeCAD models
on:
  push:
    branches:
      - main
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10'
      
      - name: Run Python script
        run: |
          python utils/freecad_thumb_generator_readme.py
      
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add thumbnails/
          git add README.md  # Or your target markdown file
          git diff --quiet && git diff --staged --quiet || (git commit -m "docs: auto-update FreeCAD table" && git push)
